### ISSUE TITLE
travis fail ./utils/blast_getBlastUtils.js

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jblast-jbconnect-hook#157]
```
$ ./utils/blast_getBlastUtils.js
appPath,checkPath /home/travis/build/GMOD/jbconnect /home/travis/build/GMOD/jbconnect/node_modules/blast-ncbi-tools
cwd /home/travis/build/GMOD/jbconnect/node_modules/blast-ncbi-tools
looking for linux x64 ...
/home/travis/build/GMOD/jbconnect/node_modules/blast-ncbi-tools/bin/getBlast.js:35
    if (err) throw err;
             ^
Error: Timed out while making data connection
    at Timeout.<anonymous> (/home/travis/build/GMOD/jbconnect/node_modules/ftp/lib/connection.js:901:12)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
NCBI Blast+ path /home/travis/build/GMOD/jbconnect/blastbin
```

**Comment by enuggetry** [comment]
Problem with ftp module in blast-ncbi-tools https://github.com/enuggetry/blast-ncbi-tools
Ftp.list not working in Travis. 
Work around when Travis uses wget.
