### ISSUE TITLE
Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jblast-jbconnect-hook#257]
```
>> { Volvox: { path: 'sample_data/json/volvox', featureMapping: 'query' },
  ChineseSpring:
   { path: 'IWGSC',
     featureMapping: 'hit',
     contigHandler: [Function: contigHandler] } } 12
/home/ericiam/jbconnect/node_modules/jblast-jbconnect-hook/bin/jbutil-ext.js:208
        console.log("inject sample track", g.dataSet[i].path);
                                                        ^

TypeError: Cannot read property 'path' of undefined
    at exec_setuptrack (/home/ericiam/jbconnect/node_modules/jblast-jbconnect-hook/bin/jbutil-ext.js:208:57)
    at Object.process (/home/ericiam/jbconnect/node_modules/jblast-jbconnect-hook/bin/jbutil-ext.js:50:13)
    at /home/ericiam/jbconnect/jbutil:59:9
    at Object.doExtScripts (/home/ericiam/jbconnect/api/services/jbutillib.js:43:15)
    at Object.<anonymous> (/home/ericiam/jbconnect/jbutil:58:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```
happening upon sails lift

**Comment by enuggetry** [comment]
resolved
https://github.com/GMOD/jblast-jbconnect-hook/commit/7f0bfdbe79a64609ba572afa337dd6ee2e93c46e
