### ISSUE TITLE
gendocs fails

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jblast-jbconnect-hook#274]
```
$ npm run gendocs
> jblast-jbconnect-hook@0.10.0 gendocs /home/ericiam/jblast
> node docs/gendocs_run.js

deleting ./docs/genapi-rst/*.rst
running jsdoc
/home/ericiam/jblast/node_modules/requizzle/lib/requizzle.js:45
        if (lookupPaths[0] === targetPath && lookupPaths[1].length === 0) {
                       ^

TypeError: Cannot read property '0' of null
    at isNativeModule (/home/ericiam/jblast/node_modules/requizzle/lib/requizzle.js:45:17)
    at Requizzle.requizzle (/home/ericiam/jblast/node_modules/requizzle/lib/requizzle.js:82:6)
    at infectProxy (/home/ericiam/jblast/node_modules/requizzle/lib/loader.js:82:28)
    at Module.targetModule.require (/home/ericiam/jblast/node_modules/requizzle/lib/loader.js:101:11)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ericiam/jblast/node_modules/jsdoc/lib/jsdoc/fs.js:7:10)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Object.load (/home/ericiam/jblast/node_modules/requizzle/lib/loader.js:112:15)
running makeapi, cwd /home/ericiam/jblast/docs
generating api.rst...
```

**Comment by enuggetry** [comment]
```
$ npm run gendocs

> jblast-jbconnect-hook@0.10.0 gendocs /home/ericiam/jblast
> node docs/gendocs_run.js

deleting ./docs/genapi-rst/*.rst
running jsdoc
Parsing /home/ericiam/jblast/api/jobservices/galaxyBlastService.js ...
Parsing /home/ericiam/jblast/api/jobservices/localBlastService.js ...
Parsing /home/ericiam/jblast/api/services/blastxml2json.js ...
Parsing /home/ericiam/jblast/api/services/entrezService.js ...
Parsing /home/ericiam/jblast/api/services/filter.js ...
Parsing /home/ericiam/jblast/api/services/filterService.js ...
Parsing /home/ericiam/jblast/api/services/galaxyUtils.js ...
Parsing /home/ericiam/jblast/api/services/jblastPostAction.js ...
Parsing /home/ericiam/jblast/api/services/offsetfix.js ...
Parsing /home/ericiam/jblast/api/services/utils.js ...
ERROR: Unable to parse a tag's type expression for source file /home/ericiam/jblast/api/services/utils.js in line 36 with tag title "param" and text "{string]} refseq reference sequence name (used for the header)": Invalid type expression "string]": Expected "!", "#", "$", "(", "-", ".", "/", "0", ":", "<", "=", "?", "@", "[]", "\\", "_", "|", "~", "‌", "‍", Unicode combining mark, Unicode decimal number, Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode punctuation connector, Unicode titlecase letter, Unicode uppercase letter, [1-9], or end of input but "]" found.
ERROR: Unable to parse a tag's type expression for source file /home/ericiam/jblast/api/services/utils.js in line 43 with tag title "param" and text "{string]} refseq reference sequence name (used for the header)": Invalid type expression "string]": Expected "!", "#", "$", "(", "-", ".", "/", "0", ":", "<", "=", "?", "@", "[]", "\\", "_", "|", "~", "‌", "‍", Unicode combining mark, Unicode decimal number, Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode punctuation connector, Unicode titlecase letter, Unicode uppercase letter, [1-9], or end of input but "]" found.
Parsing /home/ericiam/jblast/api/hooks/jblast/index.js ...
FATAL: Unable to load template: Could not locate the bindings file. Tried:
 → /home/ericiam/jblast/node_modules/deasync/build/deasync.node
 → /home/ericiam/jblast/node_modules/deasync/build/Debug/deasync.node
 → /home/ericiam/jblast/node_modules/deasync/build/Release/deasync.node
 → /home/ericiam/jblast/node_modules/deasync/out/Debug/deasync.node
 → /home/ericiam/jblast/node_modules/deasync/Debug/deasync.node
 → /home/ericiam/jblast/node_modules/deasync/out/Release/deasync.node
 → /home/ericiam/jblast/node_modules/deasync/Release/deasync.node
 → /home/ericiam/jblast/node_modules/deasync/build/default/deasync.node
 → /home/ericiam/jblast/node_modules/deasync/compiled/12.15.0/linux/x64/deasync.node
running makeapi, cwd /home/ericiam/jblast/docs
generating api.rst...
```
