### ISSUE TITLE
server crash issues

### ISSUE THREAD

**Issue by ihh** [GMOD/jblast-jbconnect-hook#279]
Reviewer comment from demo:

> I also appear
> to have crashed the instance when trying to perform a BLAST using the sequence
> underlying one of the primer pairs. Does this mean I hit a real limit which affects the
> stability of a site?

I've confirmed that (after logging in) clicking the first BLAST button in the PRIMER_PAIR_1 feature detail popup launches a BLAST job that then does not terminate.

**Comment by enuggetry** [comment]
Address issue where query or result set is very large. (reapply bpSizeLimit= setting).
https://github.com/GMOD/jbconnect/issues/175

**Comment by enuggetry** [comment]
http://graingenes.org:1337/jbrowse/?data=IWGSC&loc=chr1A%3A365715001..366846000&tracks=DNA%2Chiconf-1.1&highlight=chr1A%3A366275000..366282999

>>>>> workflowresults  {
    "type": "blastn",
    "outputDirectory": "/home/ericiam/jb1151/IWGSC/jblastdata",
    "rawOutput": false,
    "db": "/home/ericiam/jbconnect/blastdb/wheat/wheat",
    "outfmt": 5,
    "queryFile": "/home/ericiam/jb1151/IWGSC/jblastdata/blast_region1589559739997.fa",
    "outFileExt": "blastxml",
    "returnParams": true,
    "out": "/home/ericiam/jb1151/IWGSC/jblastdata/432c6530-96c8-11ea-8695-3ba48121fa95.blastxml"
}

debug: mv /home/ericiam/jb1151/IWGSC/jblastdata/432c6530-96c8-11ea-8695-3ba48121fa95.blastxml /home/ericiam/jb1151/IWGSC/jblastdata/67_1589560080324.blastxml
debug: converting blast to json
debug: blastxml2json /home/ericiam/jb1151/IWGSC/jblastdata/67_1589560080324.blastxml /home/ericiam/jb1151/IWGSC/jblastdata/67_1589560080324.json
buffer.js:645
    return this.utf8Slice(0, this.length);
                ^

Error: Cannot create a string longer than 0x3fffffe7 characters
    at Buffer.toString (buffer.js:645:17)
    at Parser.exports.Parser.Parser.parseString (/home/ericiam/jbconnect/node_modules/xml2js/lib/xml2js.js:269:15)
    at Parser.parseString (/home/ericiam/jbconnect/node_modules/xml2js/lib/xml2js.js:6:61)
    at exports.parseString (/home/ericiam/jbconnect/node_modules/xml2js/lib/xml2js.js:296:19)
    at module.exports (/home/ericiam/jbconnect/node_modules/xmljson/lib/to_json.js:17:9)
    at /home/ericiam/jbconnect/node_modules/jblast-jbconnect-hook/api/services/blastxml2json.js:51:13
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

test 1 (68) no parameters
string crash
<Hit_len>594102056</Hit_len>
xml size 1176453742

test2 (69)
max_target_seqs 100
max_hsps 3
<Hit_len>594102056</Hit_len>
66 hits
xml size 481262

test3 (70)
      max_target_seqs: 100,
      max_hsps: 5
<Hit_len>594102056</Hit_len>	  
xml size 785319
110 hits

test 4 (71)
      max_target_seqs: 200,
      max_hsps: 5
xml size 785319 (same as 70)
110 hits (same as 70)

test (72)
no parameters
handle error from xmljson module

**Comment by enuggetry** [comment]
added max_hsps blast option to jbconnect.config.js (the local config file), which reduces the number of hit results.
```
        jblast: {
            blastProfiles: {
                'wheat': {
                    'db': 'wheat',
                    'max_hsps':10
                }
            }

        },
```

**Comment by ihh** [comment]
This bug is not yet fixed.
